[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:tracker]
command=python /app/main.py run --watch
directory=/app
autostart=true
autorestart=true
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=CONFIG_PATH="%(ENV_CONFIG_PATH)s",DB_PATH="%(ENV_DB_PATH)s"

[program:webui]
command=python -m slickdeals_tracker.web
directory=/app
autostart=true
autorestart=true
startretries=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=CONFIG_PATH="%(ENV_CONFIG_PATH)s",DB_PATH="%(ENV_DB_PATH)s"
